version: '3.4'
services:
    nginx:
        build: ./model/nginx
        container_name: nginx
        restart: always 
        depends_on: 
            - mysql
            - php
            - redis
        ports: 
            - "80:80"
        volumes: 
            - ./www:/var/www/html 
    mysql:
        build: ./model/mysql
        #image: mysql:5.6
        container_name: mysql
        environment: 
            - MYSQL_ROOT_PASSWORD=123456
        depends_on: 
            - php
        ports:
            - "3306:3306"
        volumes: 
            - ./runtime/data/mysql:/var/lib/mysql
        restart: always
    php: 
       build: ./model/php
       container_name: php
       ports: 
            - "9000:9000"
       restart: always
       volumes:
            - ./www:/var/www/html
    redis: 
       build: ./model/redis
       container_name: redis
       depends_on: 
            - php
       ports: 
            - "6379:6379"
       restart: always
